apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
        - name: data-processor
          image: your-dockerhub-username/data-processor:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: data-processor
spec:
  selector:
    app: data-processor
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
